const USERNAME_IS_REQUIRED_INFO = '用户名不能为空!'
const PASSWORD_IS_REQUIRED_INFO = '密码不能为空!'
const USERNAME_IS_EXISTED_INFO = '用户已经被注册!'
const USERNAME_OR_PW_ERROR_INFO = '用户名或密码不正确!'

module.exports = {
  USERNAME_IS_REQUIRED_INFO,
  PASSWORD_IS_REQUIRED_INFO,
  USERNAME_IS_EXISTED_INFO,
  USERNAME_OR_PW_ERROR_INFO
}